# Generated by Django 4.1 on 2023-10-10 22:54

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('unique_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=1000)),
                ('image', models.ImageField(upload_to='descriptions/')),
                ('body', models.TextField()),
                ('time', models.DateTimeField(default=datetime.datetime(2023, 10, 10, 23, 54, 57, 11159))),
                ('creator', models.ForeignKey(on_delete=django.db.models.expressions.Case, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
