# Generated by Django 4.1 on 2023-10-20 06:18

import api.models
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.expressions
import django_quill.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('custom_id', models.CharField(editable=False, max_length=100, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=1000)),
                ('image', models.ImageField(blank=True, null=True, upload_to=api.models.upload_image_path)),
                ('body', django_quill.fields.QuillField()),
                ('time', models.DateTimeField(default=datetime.datetime(2023, 10, 20, 7, 18, 20, 798820))),
                ('featured', models.BooleanField(default=False)),
                ('publish', models.BooleanField(default=False)),
                ('creator', models.ForeignKey(on_delete=django.db.models.expressions.Case, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
