# Generated by Django 4.1 on 2023-10-12 03:15

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('title', models.CharField(max_length=1000)),
                ('body', models.TextField()),
                ('time', models.DateTimeField(default=datetime.datetime(2023, 10, 12, 4, 15, 7, 421012))),
                ('custom_id', models.CharField(editable=False, max_length=100, primary_key=True, serialize=False, unique=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.expressions.Case, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
