# Generated by Django 4.1 on 2023-10-26 09:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="time",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 10, 26, 10, 4, 7, 159046)
            ),
        ),
    ]
