# Generated by Django 4.1 on 2023-10-20 19:04

import datetime
from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_alter_post_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="body",
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name="post",
            name="time",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 10, 20, 20, 4, 49, 915250)
            ),
        ),
    ]
