# Generated by Django 4.1 on 2023-10-20 19:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_alter_post_body_alter_post_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="time",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 10, 20, 20, 5, 39, 992105)
            ),
        ),
    ]
