# Generated by Django 4.1 on 2023-10-16 21:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_post_publish_post_verified_alter_post_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='verified',
            new_name='featured',
        ),
        migrations.AlterField(
            model_name='post',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 16, 22, 32, 32, 805485)),
        ),
    ]
