# Generated by Django 4.1 on 2023-10-17 06:00

import datetime
from django.db import migrations, models
import django_summernote.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_verified_post_featured_alter_post_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='body',
            field=django_summernote.fields.SummernoteTextField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 17, 7, 0, 4, 172236)),
        ),
    ]
