# Generated by Django 4.1 on 2023-11-05 16:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_alter_post_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="time",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 11, 5, 17, 40, 33, 867501)
            ),
        ),
    ]
