# Generated by Django 4.1 on 2023-10-17 06:24

import datetime
from django.db import migrations, models
import django_summernote.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_post_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='body',
            field=django_summernote.fields.SummernoteTextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 17, 7, 20, 3, 580703)),
        ),
    ]
