# Generated by Django 4.1 on 2023-10-17 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersites',
            name='sites',
        ),
        migrations.AddField(
            model_name='usersites',
            name='admin_page',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='usersites',
            name='blog_page',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='usersites',
            name='home_page',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='usersites',
            name='individual_blog_post',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
