# Generated by Django 4.1 on 2023-10-28 17:35

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Scripts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("script", models.FileField(upload_to=app.models.upload_script_path)),
                ("css_file", models.FileField(upload_to=app.models.upload_css_path)),
            ],
        ),
        migrations.RemoveField(
            model_name="usersites",
            name="admin_page",
        ),
    ]
