# Generated by Django 4.1 on 2023-10-29 06:28

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_scripts_remove_usersites_admin_page"),
    ]

    operations = [
        migrations.CreateModel(
            name="CSS",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("css_file", models.FileField(upload_to=app.models.upload_css_path)),
            ],
        ),
        migrations.RemoveField(
            model_name="scripts",
            name="css_file",
        ),
    ]
