# Generated by Django 4.1 on 2023-10-26 09:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userprofile", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="token",
            name="created",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 10, 26, 10, 8, 15, 445571),
                editable=False,
            ),
        ),
        migrations.AlterField(
            model_name="token",
            name="key",
            field=models.CharField(editable=False, max_length=100),
        ),
    ]
