# Generated by Django 4.1 on 2023-10-28 17:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userprofile", "0002_alter_token_created_alter_token_key"),
    ]

    operations = [
        migrations.AlterField(
            model_name="token",
            name="created",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 10, 28, 18, 29, 52, 353528),
                editable=False,
            ),
        ),
    ]
